language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
script:
  - yarn clean && yarn build
after_success:
  - yarn travis-deploy-once && yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
